version: 2
jobs:
  build:
    docker:
      #- image: circleci/php:7.1.11-cli-node-browsers
      - image: php:7.1

    working_directory: ~/repo

    steps:
      - checkout # TODO move this back down

      - run: php --version
      # TODO REMOVE THIS
      - run: mkdir /tmp/composer-install && pushd /tmp/composer-install && php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&  php -r "if (hash_file('SHA384', 'composer-setup.php') === '544e09ee996cdf60ece3804abc52599c22b1f40f4323403c44d44fdfdd586475ca9813a858088ffbc1f233e9b180f061') { echo 'Installer verified'; } else { echo 'Installer corrupt'; unlink('composer-setup.php'); } echo PHP_EOL;" && php composer-setup.php && php -r "unlink('composer-setup.php');" && popd
      - run: php composer.phar --version

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "composer.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      #- run: composer install -n --prefer-dist
      - run: php composer.phar install -n

      - save_cache:
          paths:
            - ./vendor
          key: v1-dependencies-{{ checksum "composer.json" }}

      #- run: php ./vendor/bin/grumphp run
